export const COUNTRIES = [
  { code: "SA", name: "السعودية", flag: "🇸🇦" },
  { code: "EG", name: "مصر", flag: "🇪🇬" },
  { code: "AE", name: "الإمارات", flag: "🇦🇪" },
  { code: "QA", name: "قطر", flag: "🇶🇦" },
  { code: "KW", name: "الكويت", flag: "🇰🇼" },
  { code: "BH", name: "البحرين", flag: "🇧🇭" },
  { code: "OM", name: "عمان", flag: "🇴🇲" },
  { code: "IQ", name: "العراق", flag: "🇮🇶" },
  { code: "JO", name: "الأردن", flag: "🇯🇴" },
  { code: "LB", name: "لبنان", flag: "🇱🇧" },
  { code: "SY", name: "سوريا", flag: "🇸🇾" },
  { code: "PS", name: "فلسطين", flag: "🇵🇸" },
  { code: "MA", name: "المغرب", flag: "🇲🇦" },
  { code: "DZ", name: "الجزائر", flag: "🇩🇿" },
  { code: "TN", name: "تونس", flag: "🇹🇳" },
  { code: "LY", name: "ليبيا", flag: "🇱🇾" },
  { code: "SD", name: "السودان", flag: "🇸🇩" },
  { code: "YE", name: "اليمن", flag: "🇾🇪" },
  { code: "GB", name: "بريطانيا", flag: "🇬🇧" },
  { code: "ES", name: "إسبانيا", flag: "🇪🇸" },
  { code: "DE", name: "ألمانيا", flag: "🇩🇪" },
  { code: "FR", name: "فرنسا", flag: "🇫🇷" },
  { code: "IT", name: "إيطاليا", flag: "🇮🇹" },
  { code: "US", name: "أمريكا", flag: "🇺🇸" },
  { code: "BR", name: "البرازيل", flag: "🇧🇷" },
  { code: "AR", name: "الأرجنتين", flag: "🇦🇷" },
];
