
export const COUNTRIES = [
  { code: "SA", name: "السعودية", flag: "https://flagcdn.com/sa.svg" },
  { code: "EG", name: "مصر", flag: "https://flagcdn.com/eg.svg" },
  { code: "AE", name: "الإمارات", flag: "https://flagcdn.com/ae.svg" },
  { code: "QA", name: "قطر", flag: "https://flagcdn.com/qa.svg" },
  { code: "KW", name: "الكويت", flag: "https://flagcdn.com/kw.svg" },
  { code: "BH", name: "البحرين", flag: "https://flagcdn.com/bh.svg" },
  { code: "OM", name: "عمان", flag: "https://flagcdn.com/om.svg" },
  { code: "IQ", name: "العراق", flag: "https://flagcdn.com/iq.svg" },
  { code: "JO", name: "الأردن", flag: "https://flagcdn.com/jo.svg" },
  { code: "LB", name: "لبنان", flag: "https://flagcdn.com/lb.svg" },
  { code: "SY", name: "سوريا", flag: "https://flagcdn.com/sy.svg" },
  { code: "PS", name: "فلسطين", flag: "https://flagcdn.com/ps.svg" },
  { code: "MA", name: "المغرب", flag: "https://flagcdn.com/ma.svg" },
  { code: "DZ", name: "الجزائر", flag: "https://flagcdn.com/dz.svg" },
  { code: "TN", name: "تونس", flag: "https://flagcdn.com/tn.svg" },
  { code: "LY", name: "ليبيا", flag: "https://flagcdn.com/ly.svg" },
  { code: "SD", name: "السودان", flag: "https://flagcdn.com/sd.svg" },
  { code: "YE", name: "اليمن", flag: "https://flagcdn.com/ye.svg" },
  { code: "GB", name: "بريطانيا", flag: "https://flagcdn.com/gb.svg" },
  { code: "ES", name: "إسبانيا", flag: "https://flagcdn.com/es.svg" },
  { code: "DE", name: "ألمانيا", flag: "https://flagcdn.com/de.svg" },
  { code: "FR", name: "فرنسا", flag: "https://flagcdn.com/fr.svg" },
  { code: "IT", name: "إيطاليا", flag: "https://flagcdn.com/it.svg" },
  { code: "US", name: "أمريكا", flag: "https://flagcdn.com/us.svg" },
  { code: "BR", name: "البرازيل", flag: "https://flagcdn.com/br.svg" },
  { code: "AR", name: "الأرجنتين", flag: "https://flagcdn.com/ar.svg" },
  { code: "TR", name: "تركيا", flag: "https://flagcdn.com/tr.svg" },
  { code: "GR", name: "اليونان", flag: "https://flagcdn.com/gr.svg" },
];
